### PR TITLE
PipeTut2.3 Pull Request

### PR DESCRIPTION
**Pull request by ShahuN-107**
Hi,

As discussed in the tutorial with Dr. Labuschagne (How do titles and usernames get used on github?) and Stefan;

The velocity (According to hand iteration) should be around 2.173 m/s and memo 2.xxx m/s. I have rechecked the equations, I've also typed them for ease of reference, but there is always a chance the error might be there.

fsolve returns a velocity of ~162m/s.

I'm stuck.

### CODE REVIEW

**Comment by alchemyst** [comment]
You have used `numpy.log` which is the natural logarithm, but the formula should use base 10, which is `numpy.log10`. Also, pull requests are not an appropriate point to ask for help. I recommend creating your own repository if you would like help on a problem and just send a link in a mail.

**Comment by JLFlyer1** [comment]
Sorted?

Log_10 vs log_e?

Regards,

Dr. Johan Labuschagné

PrEng, BEng (Chem), PhD

Engineering 1 Building, Room 8-14

Department of Chemical Engineering

University of Pretoria

Pretoria

0002

Cell: +27 (0) 83 307 4544

Tel:  +27 (0) 12 420 3020

Fax: +27 (0) 12 420 5048

email:  mailto:johan.labuschagne@up.ac.za johan.labuschagne@up.ac.za

web:  http://www.up.ac.za/fjlabuschagne http://www.up.ac.za/fjlabuschagne

This message and attachments are subject to a disclaimer. Please refer to  http://www.it.up.ac.za/documentation/governance/disclaimer/ www.it.up.ac.za/documentation/governance/disclaimer/ for full details. 

Hierdie boodskap en aanhangsels is aan 'n vrywaringsklousule onderhewig. Volledige besonderhede is by  http://www.it.up.ac.za/documentation/governance/disclaimer/ www.it.up.ac.za/documentation/governance/disclaimer/ beskikbaar.

**Comment by ShahuN-107** [comment]
Yes, thanks.

Apologies Carl, will do that in future.

**Comment by ShahuN-107** [comment]
Apologies, will create an e-mail link to a repository in future.

Using `numpy.log10` yields the velocity to be 70.4m/s, which is still incorrect. So not quite there yet.

*edit:link
https://github.com/ShahuN-107/CIO

**Pull request closed without merging**
